import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  GetCatogories,
  GetPostBySlug,
  getPosts,
  GetRecentPost,
} from "../Server/Index.js";
import { useRouter } from "next/router";
import Blogs from "../Components/Blogs";
import Navbar from "../Components/Navbar";
import RecentPosts from "./Recent";
import moment from "moment";
import Categories from "./Categories";
// import background from "/pexels-picography-4458.jpg";

export default function Home({ posts, Recnt, cateGories, post }) {
  const router = useRouter();
  console.log(router);
  return (
    <div className="container mx-auto px-10 mb-10 bg-gray-100 rounded-xl  lg:py-2 w-screen h-s">
      <Head>
        <title className="">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
      {/* <h1 className="text-center">Armmaan Khan</h1> */}

      {console.log(posts[3])}
      {console.log(post)}
      {console.log(Recnt ? Recnt[0].featuredImage.url : "not ")}
      {console.log(cateGories[0].slug)}
      <div className="bg-white shadow-md w-64 ">
        <h1 className="text-3xl px-4 py-4 font-extrabold text-center text-white bg-purple-700 ">
          Categories
        </h1>
        {cateGories.map((data, ind) => (
          <Categories
            title={data?.name}
            href={data.slug}
            // img={data.node.featuredImage?.url}
            key={data.title}
          />
        ))}
      </div>
      <div className="lg:flex ">
        {/* <Category href={cateGories[0].slug} title={cateGories[0].title} /> */}

        <div className="w-full shadow-md lg:p-5 lg:w-[70%]">
          {posts.map((data, ind) => (
            <Blogs
              title={data?.node.slug}
              name={data.node.author.name}
              excerpt={data.node.excerpt}
              time={data.node.createdBy.createdAt}
              bio={data.node.author.bio}
              slug={data.node.slug}
              img={data.node.featuredImage?.url}
              key={data.title}
            />
          ))}
        </div>
        <div className="w-[30%] border-2   invisible flex flex-wrap lg:fixed  lg:bottom-12 top-32 lg:right-20 lg:visible shadow-lg  rounded-lg">
          <h1 className="text-sm  border-b-2 border-black text-black h-8 p-2 font-extrabold rounded w-full text-center texwhite ">
            Recent Post
          </h1>
          {Recnt.map((data, ind) => {
            return (
              <div className="m-4 ">
                <RecentPosts
                  img={data.featuredImage?.url}
                  href={`posts/${data.slug}`}
                  time={moment(data.createdAt).format("MMM DD Y")}
                  title={data.title}
                />
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
export async function getStaticProps({ params }) {
  const posts = (await getPosts()) || [];
  const Recnt = (await GetRecentPost()) || [];
  const cateGories = (await GetCatogories()) || [];
  const getBySlug = (await GetPostBySlug("web-dev")) || [];
  return {
    props: { posts, Recnt, cateGories, post: getBySlug },
    // props: { Recnt },
  };
  // return {
  // };
}
// export async function getStaticPaths() {
//   const posts = (await getPosts()) || [];
//   return {
//     paths: posts.map(({ node: { slug } }) => ({ params: { slug } })),
//     fallback: false,
//   };
// }
