import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  GetCatogories,
  GetPostBySlug,
  getPosts,
  GetRecentPost,
} from "../Server/Index.js";
import { useRouter } from "next/router";
import Blogs from "../Components/Blogs";
import Navbar from "../Components/Navbar";
import RecentPosts from "./Recent";
import moment from "moment";
import Categories from "./Categories";
import { useState } from "react";
import { useEffect } from "react";
// import background from "/pexels-picography-4458.jpg";

export default function Home({ posts, Recnt, cateGories, post }) {
  return (
    <div className=" lg:mx-8 lg:mb-10 shadow-md bg-purple-90 shadow-blue-gray-500 m-3 rounded-xl  lg:py-2 lg:w-[1450px] h-s">
      <Head>
        <title className="">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Dancing+Script:wght@500;600;700&family=Fredoka+One&family=Fredoka:wght@600&family=Lato:wght@700&family=League+Gothic&family=Lobster&family=Merriweather&family=Poppins&family=Roboto:ital,wght@0,700;1,500&family=Silkscreen&family=Sora&family=Tiro+Devanagari+Hindi:ital@1&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      {console.log(posts)}
      {console.log(post)}
      {console.log(Recnt ? Recnt[0].featuredImage.url : "not ")}
      {console.log(cateGories[0].slug)}
      {/* <div className="bg-white shadow-md w-64 ">
        <h1 className="text-3xl px-4 py-4 font-extrabold text-center text-white bg-purple-700 ">
          Categories
        </h1>
        {cateGories.map((data, ind) => (
          <Categories title={data?.name} href={data.slug} key={data.title} />
        ))}
      </div> */}
      <div className="lg:flex lg:p-3 lg:m-3">
        <div className="w-full shadow-md shadow-transparent  lg:p-5  lg:w-[70%]">
          {posts.map((data, ind) => (
            <Blogs
              title={data?.node.title}
              name={data.node.author.name}
              excerpt={data.node.excerpt}
              time={data.node.createdBy.createdAt}
              bio={data.node.author.bio}
              slug={data.node.slug}
              img={data.node.featuredImage?.url}
              key={data.title}
            />
          ))}
        </div>
        <div className="w-[30%] bg-white gap-4 my-12 invisible lg:visible h-screen  rounded-lg">
          <h1 className="text-sm  border-b-2 border-black text-black  p-2 font-extrabold rounded w-full text-center texwhite ">
            Recent Post
          </h1>
          {Recnt.map((data, ind) => {
            return (
              <div className="m-4  h-32 ">
                <RecentPosts
                  img={data.featuredImage?.url}
                  href={`post/${data.slug}`}
                  time={moment(data.createdAt).format("MMM DD Y")}
                  title={data.title}
                />
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
export async function getStaticProps({ params }) {
  const posts = (await getPosts()) || [];
  const Recnt = (await GetRecentPost()) || [];
  const cateGories = (await GetCatogories()) || [];
  const getBySlug = (await GetPostBySlug("web-dev")) || [];
  return {
    props: { posts, Recnt, cateGories, post: getBySlug },
    // props: { Recnt },
  };
  // return {
  // };
}
