import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GetCatogories, getPosts, GetRecentPost } from "../Server/Index.js";
import Blogs from "../Components/Blogs";
import Navbar from "../Components/Navbar";
import RecentPosts from "./Recent";
import moment from "moment";
import Categories from "./Categories";
// import background from "/pexels-picography-4458.jpg";

export default function Home({ posts, Recnt, cateGories }) {
  return (
    <div className="container mx-auto px-10 mb-10 bg-teal-500 rounded-xl  lg:py-7 w-screen h-s">
      <Head>
        <title className="">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
      {/* <h1 className="text-center">Armmaan Khan</h1> */}

      {console.log(posts[3])}
      {console.log(Recnt ? Recnt[0].featuredImage.url : "not ")}
      {console.log(cateGories[0].slug)}
      <div className="bg-white shadow-md w-64 ">
        <h1 className="text-3xl px-4 py-4 font-extrabold text-center text-white bg-teal-700 ">
          Categories
        </h1>
        {cateGories.map((data, ind) => (
          <Categories
            title={data?.name}
            href={data.slug}
            // img={data.node.featuredImage?.url}
            key={data.title}
          />
        ))}
      </div>
      <div className="lg:flex ">
        {/* <Category href={cateGories[0].slug} title={cateGories[0].title} /> */}

        <div className="w-full shadow-md lg:p-5 lg:w-[70%]">
          {posts.map((data, ind) => (
            <Blogs
              title={data?.node.slug}
              name={data.node.author.name}
              excerpt={data.node.excerpt}
              time={data.node.createdBy.createdAt}
              bio={data.node.author.bio}
              slug={data.node.slug}
              img={data.node.featuredImage?.url}
              key={data.title}
            />
          ))}
        </div>
        <div className="w-[30%] invisible lg:visible shadow-lg h-screen m-4 rounded-lg">
          {Recnt.map((data, ind) => {
            return (
              <RecentPosts
                img={data.featuredImage?.url}
                href={`posts/${data.slug}`}
                time={moment(data.createdAt).format("MMM DD Y")}
                title={data.title}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
}
export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  const Recnt = (await GetRecentPost()) || [];
  const cateGories = (await GetCatogories()) || [];
  return {
    props: { posts, Recnt, cateGories },
    // props: { Recnt },
  };
  // return {
  // };
}
